#######################################
# THE ONLY VARIABLE YOU MUST CHANGE!! #
#######################################
user: vagrant




#####################################
# VARIABLES YOU SHOULD NOT CHANGE!! #
#####################################
ushome: /home/{{ user }}
inventory: /home/{{ user }}/ansible/docker-awx/roles/awx/inventory
invdest: /home/{{ user }}/awx-17.1.0/installer
