---
  - name: Install zip and pwgen
    become: yes
    package:
      name:
        - zip
        - pwgen
      state: present

  - name: Copy zip file to /home path
    become_user: "{{ user }}"
    copy:
      src: /home/vagrant/ansible/docker-awx/roles/awx/awx-17.1.0.zip
      dest: "{{ ushome }}"

  - name: Unzip AWX archive
    become_user: "{{ user }}"
    unarchive:
      src: "{{ ushome }}/awx-17.1.0.zip"
      dest: "{{ ushome }}"
      remote_src: yes

  - name: Generate password
    command: pwgen -N 1 -s 40
    register: pw_gen

  - name: Copy inventory file to playbook path
    become_user: "{{ user }}"
    copy:
      src: "{{ inventory }}"
      dest: "{{ invdest }}"

  - name: Run AWX installation
    become_user: "{{ user }}"
    command: ansible-playbook -i inventory install.yml
    args:
      chdir: /home/vagrant/awx-17.1.0/installer

      #  - name: enable port 80
    #    become: yes
#    firewalld:        
            #      zone: public
      #      port: 80/tcp
      #      permanent: true
      #      state: enabled

      #  handlers:
          #  - name: Restart firewalld
    #    become: yes
    #    service:
            #      name: firewalld
      #     state: restarted
