---
  - name: Install zip and pwgen
    become: yes
    package:
      name:
        - zip
        - pwgen
      state: present

  - name: Download AWX zip file
    get_url:
      url: "https://github.com/ansible/awx/archive/{{ version }}.zip"
      dest: "{{ ushome }}"

  - name: Unzip AWX archive
    become_user: "{{ user }}"
    unarchive:
      src: "{{ ushome }}/awx-17.1.0.zip"
      dest: "{{ ushome }}"
      remote_src: yes

  - name: Delete file .zip
    file:
      path: "{{ ushome }}/awx-{{ version }}.zip"
      state: absent

  - name: Generate password
    command: pwgen -N 1 -s 40
    register: pw_gen

  - name: Copy inventory file to playbook path
    become_user: "{{ user }}"
    copy:
      src: inventory
      dest: "{{ invdest }}"

  - name: Replace secret_key in inventory file
    lineinfile:
      dest: "{{ invdest }}/inventory"
      line: "secret_key={{ pw_gen.stdout }}"
      regexp: "^secret_key=secureKey"
      state: present

  - name: Run AWX installation
    become_user: "{{ user }}"
    command: ansible-playbook -i inventory install.yml
    args:
      chdir: "{{ ushome }}/awx-{{ version }}/installer"

      #  - name: enable port 80
    #    become: yes
#    firewalld:        
            #      zone: public
      #      port: 80/tcp
      #      permanent: true
      #      state: enabled

      #  handlers:
          #  - name: Restart firewalld
    #    become: yes
    #    service:
            #      name: firewalld
      #     state: restarted
