---
  - name: Install curl and wget
    yum:
      name:
        - curl
        - wget
      state: latest

  - name: Download the latest Docker Compose binary
    shell: curl -s https://api.github.com/repos/docker/compose/releases/latest | grep browser_download_url  | grep docker-compose-linux-x86_64 | cut -d '"' -f 4 | wget -qi -
    args:
      executable: /bin/bash

  - name: Give executable permission to the binary
    file:
      path: docker-compose-linux-x86_64
      mode: u+x

  - name: Move Docker Compose binary to path
    command: mv docker-compose-linux-x86_64 "{{ path }}"

  - name: Give all permissions to file
    file:
      path: "{{ path }}"
      mode: "777"

  - name: Create Docker group
    group:
      name: docker
      state: present

  - name: Add user to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes

  - name: Download Docker Compose script
    get_url:
      url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose
      dest: /etc/bash_completion.d/docker-compose

  - name: Source Docker Compose script
    shell: source /etc/bash_completion.d/docker-compose
    args:
      executable: /bin/bash

  - name: Install Docker-Compose Python module
    pip:
      name: docker-compose
      executable: pip3

  - name: Give all permissions to a file
    file:
      path: "{{ file }}" 
      mode: "777"
